namespace BeDynamic.PropertyManagement;

using BeDynamic.PropertyWizard;
using Microsoft.Finance.Dimension;
using Microsoft.Finance.GeneralLedger.Account;
using Microsoft.Inventory.Item;
using Microsoft.Inventory.Item.Attribute;
using Microsoft.Projects.Project.Job;
using Microsoft.Sales.Customer;
using Microsoft.Sales.Document;
using Microsoft.Sales.History;
using Microsoft.Sales.Pricing;
using System.Security.User;

permissionset 82500 "BeDyn Property Mgt."
{
    Assignable = true;
    Caption = 'Gestión de Propiedades';

    Permissions =
        tabledata "BeDyn Property Mgt. Setup" = RIMD,
        tabledata "BeDyn Property Owner" = RIMD,
        tabledata "BeDyn Property" = RIMD,
        tabledata "BeDyn Property Room" = RIMD,
        tabledata "BeDyn Property Contract" = RIMD,
        tabledata "BeDyn Tenant" = RIMD,
        tabledata "BeDyn Property Service" = RIMD,
        tabledata "BeDyn Reservation" = RIMD,
        tabledata "BeDyn Reservation Service" = RIMD,
        tabledata "BeDyn Portal" = RIMD,
        tabledata "BeDyn Property Portal Link" = RIMD,
        tabledata "BeDyn Property Status" = RIMD,
        tabledata "BeDyn Prop. Text Translation" = RIMD,
        tabledata "BeDyn Property Type" = RIMD,
        tabledata "BeDyn Room Type" = RIMD,
        tabledata "BeDyn Stay Type" = RIMD,
        tabledata "BeDyn Amenity Type" = RIMD,
        tabledata "BeDyn Amenity" = RIMD,
        tabledata "BeDyn Property Amenity" = RIMD,
        tabledata "BeDyn Property Image" = RIMD,
        tabledata "BeDyn Deposit" = RIMD,
        tabledata "BeDyn Property Cue" = RIMD,
        tabledata "BeDyn Customer Type" = RIMD,
        tabledata "BeDyn Guest Type" = RIMD,
        tabledata "Sales Price" = RIMD,
        tabledata "Sales Header" = RIM,
        tabledata "Sales Line" = RIMD,
        tabledata "Sales Invoice Header" = R,
        tabledata "Sales Invoice Line" = R,
        tabledata Customer = R,
        tabledata "G/L Account" = R,
        tabledata Item = RM,
        tabledata "Item Variant" = RM,
        // Numeración enlazada de los cuatro maestros: el renombrado en cascada
        // toca el proyecto, el valor de dimensión y sus dimensiones por defecto.
        tabledata Job = RM,
        tabledata "Dimension Value" = RM,
        tabledata "Default Dimension" = RM,
        tabledata "User Setup" = R,
        tabledata "BeDyn Property Setup" = R,
        tabledata "Item Attribute" = R,
        tabledata "Item Attribute Value" = R,
        tabledata "Item Attribute Value Mapping" = R,
        table "BeDyn Property Mgt. Setup" = X,
        table "BeDyn Property Owner" = X,
        table "BeDyn Property" = X,
        table "BeDyn Property Room" = X,
        table "BeDyn Property Contract" = X,
        table "BeDyn Tenant" = X,
        table "BeDyn Property Service" = X,
        table "BeDyn Reservation" = X,
        table "BeDyn Reservation Service" = X,
        table "BeDyn Portal" = X,
        table "BeDyn Property Portal Link" = X,
        table "BeDyn Property Status" = X,
        table "BeDyn Prop. Text Translation" = X,
        table "BeDyn Property Type" = X,
        table "BeDyn Room Type" = X,
        table "BeDyn Stay Type" = X,
        table "BeDyn Amenity Type" = X,
        table "BeDyn Amenity" = X,
        table "BeDyn Property Amenity" = X,
        table "BeDyn Property Image" = X,
        table "BeDyn Deposit" = X,
        table "BeDyn Property Cue" = X,
        table "BeDyn Customer Type" = X,
        table "BeDyn Guest Type" = X,
        codeunit "BeDyn Prop. Reservation Mgt." = X,
        codeunit "BeDyn Property Text Mgt." = X,
        codeunit "BeDyn Property Price Mgt." = X,
        codeunit "BeDyn Property Billing Mgt." = X,
        codeunit "BeDyn Property Online Map Mgt." = X,
        codeunit "BeDyn Property Picture Sync" = X,
        codeunit "BeDyn Property Image Import" = X,
        codeunit "BeDyn Property Code Sync" = X,
        codeunit "BeDyn Deposit Posting" = X,
        codeunit "BeDyn Property Upgrade" = X,
        page "BeDyn Property Mgt. Setup" = X,
        page "BeDyn Property Owner List" = X,
        page "BeDyn Property Owner Card" = X,
        page "BeDyn Property List" = X,
        page "BeDyn Property Card" = X,
        page "BeDyn Property Room List" = X,
        page "BeDyn Property Room Details" = X,
        page "BeDyn Property Contract List" = X,
        page "BeDyn Property Contract Card" = X,
        page "BeDyn Tenant List" = X,
        page "BeDyn Tenant Card" = X,
        page "BeDyn Property Service List" = X,
        page "BeDyn Reservation List" = X,
        page "BeDyn Reservation Card" = X,
        page "BeDyn Reservation Services" = X,
        page "BeDyn Portal List" = X,
        page "BeDyn Property Portal Links" = X,
        page "BeDyn Portal Web Viewer" = X,
        page "BeDyn Property Statuses" = X,
        page "BeDyn Property Item Prices" = X,
        page "BeDyn Property Types" = X,
        page "BeDyn Room Types" = X,
        page "BeDyn Stay Types" = X,
        page "BeDyn Customer Types" = X,
        page "BeDyn Guest Types" = X,
        page "BeDyn Property Room Card" = X,
        page "BeDyn Amenity Types" = X,
        page "BeDyn Amenities" = X,
        page "BeDyn Property Amenity List" = X,
        page "BeDyn Room Avail. Calendar" = X,
        page "BeDyn Property Image Gallery" = X,
        page "BeDyn Property Image List" = X,
        page "BeDyn Prop. Text Translations" = X,
        page "BeDyn Prop. Text Transl. Card" = X,
        page "BeDyn Deposit List" = X,
        page "BeDyn Deposit Card" = X,
        page "BeDyn Property Activities" = X,
        page "BeDyn Property Manager RC" = X,
        page "BeDyn Property RC Headline" = X,
        report "BeDyn Prop. Amenity Inventory" = X,
        report "BeDyn Gen. Monthly Rent Inv." = X,
        report "BeDyn Property Code Check" = X;
}
